# Generated by Django 5.1.7 on 2025-04-15 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0004_appointmentcategory_doctor_medicalspecialty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_glucose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('daily_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('health_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
